/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-04-20 06:45:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.bdhRes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bdhRes2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/js_kmw.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=38fdb692fa19c0a5b6b48cdf0d99203b\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/css_kmw/res_css/rescommon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/css_kmw/res_css/bdhRes2.css\">\r\n");
      out.write("\r\n");
      out.write("<script>	\r\n");
      out.write("\r\n");
      out.write("function showMap() {\r\n");
      out.write("	  var mapDiv = document.getElementById(\"map\");\r\n");
      out.write("	  mapDiv.style.display = \"block\";\r\n");
      out.write("	  var options = {\r\n");
      out.write("	    center: new kakao.maps.LatLng(36.348735, 127.4374054),\r\n");
      out.write("	    level: 3\r\n");
      out.write("	  };\r\n");
      out.write("	  var map = new kakao.maps.Map(mapDiv, options);\r\n");
      out.write("	  var markerPosition = new kakao.maps.LatLng(36.348735, 127.4374054);\r\n");
      out.write("	  var marker = new kakao.maps.Marker({\r\n");
      out.write("	    position: markerPosition\r\n");
      out.write("	  });\r\n");
      out.write("	  marker.setMap(map);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		$(function(){\r\n");
      out.write("			$.setStepStyle(1);\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			$('#searchBtn').on('click',function(){\r\n");
      out.write("				$('#nameVal').val(\"\");\r\n");
      out.write("				addr = $('#inputAddr').val().trim();\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"");
      out.print(request.getContextPath());
      out.write("/BdhRes2.do\",\r\n");
      out.write("					type : \"post\",\r\n");
      out.write("					data : {\"addr\":addr},\r\n");
      out.write("					success : function(res){\r\n");
      out.write("						code=\"<table id='bdhTb'><tr><td>지 역</td><td>헌혈의집 이름</td><td>주 소</td><td>전화번호</td><td >선 택</td></tr>\";\r\n");
      out.write("						if(res.length == 0){ // 검색 결과가 없을 경우\r\n");
      out.write("		                    code += \"<tr><td colspan='5' style='text-align:center; font-weight:bold;'>헌혈의집 정보가 존재하지 않습니다.</td></tr>\";\r\n");
      out.write("		                } else {\r\n");
      out.write("		                    $.each(res,function(i,v){\r\n");
      out.write("		                        code+=\"<tr><td>\"+v.bdh_region+\"</td><td style='font-weight: bold;'>\"+\r\n");
      out.write("		                        		v.client_name+\"</td><td>\"+v.client_addr+\"</td><td>\"+v.client_tel+\"</td><td style='text-align: center;'><input type='button' id='selectBdh' value='선 택' onclick='showMap()'></td></tr>\";\r\n");
      out.write("		                    });\r\n");
      out.write("		                }\r\n");
      out.write("						code+=\"</table>\";\r\n");
      out.write("						\r\n");
      out.write("						$('#addrCol').html(code);\r\n");
      out.write("						$('#bdhTb tr:eq(0)').css({'background-color':'#f6f6f6','text-align':'center','font-weight':'bold'});\r\n");
      out.write("						$('#bdhTb td').css('border-bottom', '1px solid #dad8d9');\r\n");
      out.write("						\r\n");
      out.write("					},\r\n");
      out.write("					error : function(xhr){\r\n");
      out.write("						alert(\"status : \"+xhr.status);\r\n");
      out.write("					},\r\n");
      out.write("					dataType : 'json'\r\n");
      out.write("				})\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("			$(document).on('click','#selectBdh',function(){		\r\n");
      out.write("				bdhName = $(this).closest('tr').find('td:eq(1)').text();\r\n");
      out.write("				bdhAddr = $(this).closest('tr').find('td:eq(2)').text();\r\n");
      out.write("				bdhTel = $(this).closest('tr').find('td:eq(3)').text();\r\n");
      out.write("				\r\n");
      out.write("				$('#nameVal').val(bdhName);\r\n");
      out.write("				$('#addrVal').val(bdhAddr);\r\n");
      out.write("				$('#telVal').val(bdhTel);\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("			$('#nextBtn').on('click',function(){\r\n");
      out.write("				cnt = $('input[name=\"type\"]:checked').length;\r\n");
      out.write("				if(cnt == 0){\r\n");
      out.write("					alert('헌혈종류를 입력하세요');\r\n");
      out.write("					return false;\r\n");
      out.write("				}else if($('#addrVal').val()==''){\r\n");
      out.write("					alert('헌혈의집을 입력하세요');\r\n");
      out.write("					return false;\r\n");
      out.write("				}else{\r\n");
      out.write("					return true;\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<div id=\"text\">\r\n");
      out.write("				<p>헌혈의집 예약</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"stepBox\">\r\n");
      out.write("				<div class=\"step\">\r\n");
      out.write("					<span>STEP1</span><br>\r\n");
      out.write("					<p>유의사항</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"step\">\r\n");
      out.write("					<span>STEP2</span><br>\r\n");
      out.write("					<p>헌혈의집 선택</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"step\">\r\n");
      out.write("					<span>STEP3</span><br>\r\n");
      out.write("					<p>날짜 및 시간 선택</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"step\">\r\n");
      out.write("					<span>STEP4</span><br>\r\n");
      out.write("					<p>개인정보입력 및 확인</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("	<form action=\"/BdhRes3.do\" method=\"post\">\r\n");
      out.write("		<div id=\"select\">\r\n");
      out.write("			<div class = \"selectValue\">\r\n");
      out.write("				<div class=\"sTitle\">\r\n");
      out.write("					<p>헌혈종류</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sValue\">\r\n");
      out.write("					<input type=\"radio\" name=\"type\" value=\"전혈\">전혈\r\n");
      out.write("					<input type=\"radio\" name=\"type\" value=\"혈장\">혈장\r\n");
      out.write("					<input type=\"radio\" name=\"type\" value=\"혈소판\">혈소판\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class = \"selectValue\">\r\n");
      out.write("				<div class=\"sTitle\">\r\n");
      out.write("					<p>편의시설 선택</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sValue\">\r\n");
      out.write("					<input type=\"checkbox\">주차가능\r\n");
      out.write("					<input type=\"checkbox\">지하철인근\r\n");
      out.write("					<input type=\"checkbox\">인터넷이용\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class = \"selectValue\">\r\n");
      out.write("				<div class=\"sTitle\">\r\n");
      out.write("					<p>헌혈의집 검색</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sValue\">\r\n");
      out.write("					<input type=\"text\" placeholder=\"헌혈의집 명 또는 헌혈의집 주소를 입력해주세요\" name=\"bdhAddr\" id=\"inputAddr\">\r\n");
      out.write("					<input type=\"button\" id=\"searchBtn\" value=\"검 색\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class = \"selectValue\">\r\n");
      out.write("				<div class=\"sTitle\">\r\n");
      out.write("					<p>예약할 헌혈의집 이름</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sValue\">\r\n");
      out.write("					<input type=\"text\" name=\"nameVal\" id=\"nameVal\" readonly=\"readonly\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<input type=\"hidden\" name=\"addrVal\" id=\"addrVal\">\r\n");
      out.write("		<input type=\"hidden\" name=\"telVal\" id=\"telVal\">\r\n");
      out.write("		<div id=\"result\">\r\n");
      out.write("			<div id=\"addrCol\">\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"map\" style=\"display: none;width:80%;height:400px;\"></div>\r\n");
      out.write("		\r\n");
      out.write("		<script>\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("		<div id=\"btnwrap\">\r\n");
      out.write("			<input type=\"button\" value=\"이 전\" class=\"btn\" id=\"preBtn\" onclick=\"location.href='/BdhRes1.do'\">\r\n");
      out.write("			<input type=\"submit\" value=\"다 음\" class=\"btn\" id=\"nextBtn\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
