/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-04-13 08:31:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/layout/common/common_bottom.jsp", Long.valueOf(1680943727576L));
    _jspx_dependants.put("/view/layout/common/common_top.jsp", Long.valueOf(1680943727575L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <script type=\"text/javascript\">mypath = '");
      out.print( request.getContextPath() );
      out.write("'</script>\r\n");
      out.write("  <!-- Jquery -->\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script> \r\n");
      out.write("  <!-- BootStrap-->\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <title>RedPlus</title>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 공통 main CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/main.css\" />\r\n");
      out.write("<!-- 개인 CSS 불러오기 -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/css_hkt.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/css_jhs.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/css_kmw.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/css_lsj.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/css_omn.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- 공통 Js -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/main.js\"\"></script>\r\n");
      out.write("<!-- 개인 Js -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/js_hkt.js\"\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/js_jhs.js\"\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/js_kmw.js\"\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/js_lsj.js\"\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/js_omn.js\"\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--브라우저 스타일 초기화-->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css\" />\r\n");
      out.write("  <!--Google Fonts - 나눔고딕-->\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" />\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700&display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("  <!--Google Material Icons-->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" />\r\n");
      out.write("\r\n");
      out.write("  <!--Open Graph-->\r\n");
      out.write("  <!--http://ogp.me/-->\r\n");
      out.write("  <meta property=\"og:type\" content=\"website\" />\r\n");
      out.write("  <meta property=\"og:site_name\" content=\"RedPlus\" />\r\n");
      out.write("  <meta property=\"og:title\" content=\"레드플러스, 사랑을 나눠요!\" />\r\n");
      out.write("  <meta property=\"og:description\" content=\"레드플러스와 헌혈 함께해요!.\" />\r\n");
      out.write("  <meta property=\"og:image\" content=\"#\" />\r\n");
      out.write("  <meta property=\"og:url\" content=\"https://ddit.or.kr\" />\r\n");
      out.write("\r\n");
      out.write("  <!--Twitter Card-->\r\n");
      out.write("  <!--https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started-->\r\n");
      out.write("  <meta property=\"twitter:card\" content=\"summary\" />\r\n");
      out.write("  <meta property=\"twitter:site\" content=\"RedPlus\" />\r\n");
      out.write("  <meta property=\"twitter:title\" content=\"레드플러스, 사랑을 나눠요!\" />\r\n");
      out.write("  <meta property=\"twitter:description\" content=\"레드플러스는 헌혈 캠페인을 하고있습니다.\" />\r\n");
      out.write("  <meta property=\"twitter:image\" content=\"#\" />\r\n");
      out.write("  <meta property=\"twitter:url\" content=\"https://ddit.or.kr\" />\r\n");
      out.write("\r\n");
      out.write("  <!--파비콘-->\r\n");
      out.write("  <!--<link rel=\"shortcut icon\" href=\"favicon.ico\" />-->\r\n");
      out.write("  <link rel=\"icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/favicon/favicon.png\" />\r\n");
      out.write("  <!--브라우저 스타일 초기화-->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css\" />\r\n");
      out.write("  <!--Google Fonts - 나눔고딕-->\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" />\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700&display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("  <!--Google Material Icons-->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--GSAP & ScrollToPlugin-->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/gsap.min.js\" integrity=\"sha512-IQLehpLoVS4fNzl7IfH8Iowfm5+RiMGtHykgZJl9AWMgqx0AmJ6cRWcB+GaGVtIsnC4voMfm8f2vwtY+6oPjpQ==\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/ScrollToPlugin.min.js\" integrity=\"sha512-nTHzMQK7lwWt8nL4KF6DhwLHluv6dVq/hNnj2PBN0xMl2KaMm1PM02csx57mmToPAodHmPsipoERRNn4pG7f+Q==\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <!--Swiper-->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper@6.8.4/swiper-bundle.min.css\" />\r\n");
      out.write("  <script src=\"https://unpkg.com/swiper@6.8.4/swiper-bundle.min.js\"></script>\r\n");
      out.write("  <!--ScrollMagic-->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.8/ScrollMagic.min.js\"></script>\r\n");
      out.write("  <!--Lodash-->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.20/lodash.min.js\" integrity=\"sha512-90vH1Z83AJY9DmlWa8WkjkV79yfS2n2Oxhsi2dZbIv0nC4E6m5AbH8Nh156kkM7JePmqD6tcZsfad1ueoaovww==\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body></body>\r\n");
      out.write("\r\n");
      out.write("  <!--HEADER-->\r\n");
      out.write("  <header>\r\n");
      out.write("    <div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("      <a href=\"/\" class=\"logo\">\r\n");
      out.write("        <img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/redplus_logo.png\" alt=\"REDPLUS\" />\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      <ul class=\"main-menu\">\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <div class=\"item__name\">마이페이지</div>\r\n");
      out.write("          <div class=\"item__contents\">\r\n");
      out.write("            <div class=\"contents__menu\">\r\n");
      out.write("              <ul class=\"inner\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>보유헌혈증</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li>-</li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>헌혈이력 조회</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li>-</li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>내가 쓴글 조회</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li>-</li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>회원정보 수정</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li>-</li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                    <li></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contents__texture\">\r\n");
      out.write("              <div class=\"inner\">\r\n");
      out.write("                <h4>헌혈로 사랑을 나눠요</h4>\r\n");
      out.write("                <p>레드플러스에서 헌혈 예약을 할 수 있습니다.</p>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <div class=\"item__name\">헌혈예약</div>\r\n");
      out.write("          <div class=\"item__contents\">\r\n");
      out.write("            <div class=\"contents__menu\">\r\n");
      out.write("              <ul class=\"inner\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4></h4>\r\n");
      out.write(" \r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4></h4>\r\n");
      out.write("                \r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>헌혈의집 예약</h4>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>지정헌혈 예약</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                   \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4></h4>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contents__texture\">\r\n");
      out.write("              <div class=\"inner\">\r\n");
      out.write("                <h4>헌혈로 사랑을 나눠요</h4>\r\n");
      out.write("                <p>레드플러스에서 헌혈 예약을 할 수 있습니다.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <div class=\"item__name\">헌혈증기부</div>\r\n");
      out.write("          <div class=\"item__contents\">\r\n");
      out.write("            <div class=\"contents__menu\">\r\n");
      out.write("              <ul class=\"inner\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4></h4>\r\n");
      out.write(" \r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4></h4>\r\n");
      out.write("                \r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4></h4>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>기부하기</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                   \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4></h4>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contents__texture\">\r\n");
      out.write("              <div class=\"inner\">\r\n");
      out.write("                <h4>헌혈로 사랑을 나눠요</h4>\r\n");
      out.write("                <p>레드플러스에서 헌혈 예약을 할 수 있습니다.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <div class=\"item__name\">커뮤니티</div>\r\n");
      out.write("          <div class=\"item__contents\">\r\n");
      out.write("            <div class=\"contents__menu\">\r\n");
      out.write("              <ul class=\"inner\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4></h4>\r\n");
      out.write(" \r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4></h4>\r\n");
      out.write("                \r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4></h4>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4></h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                   \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>커뮤니티</h4>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contents__texture\">\r\n");
      out.write("              <div class=\"inner\">\r\n");
      out.write("                <h4>헌혈로 사랑을 나눠요</h4>\r\n");
      out.write("                <p>레드플러스에서 헌혈 예약을 할 수 있습니다.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <div class=\"item__name\">헌혈정보</div>\r\n");
      out.write("          <div class=\"item__contents\">\r\n");
      out.write("            <div class=\"contents__menu\">\r\n");
      out.write("              <ul class=\"inner\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>헌혈의 필요성</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li>마이 스타벅스 리워드 소개</li>\r\n");
      out.write("                    <li>등급 및 혜택</li>\r\n");
      out.write("                    <li>스타벅스 별</li>\r\n");
      out.write("                    <li>자주하는 질문</li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>헌혈과정</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li>스타벅스 카드 소개</li>\r\n");
      out.write("                    <li>스타벅스 카드 갤러리</li>\r\n");
      out.write("                    <li>등록 및 조회</li>\r\n");
      out.write("                    <li>충전 및 이용안내</li>\r\n");
      out.write("                    <li>분실신고/환불신청</li>\r\n");
      out.write("                    <li>자주하는 질문</li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>혈액 관리시스템</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li>스타벅스 카드 e-Gift 소개</li>\r\n");
      out.write("                    <li>이용안내</li>\r\n");
      out.write("                    <li>선물하기</li>\r\n");
      out.write("                    <li>자주하는 질문</li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contents__texture\">\r\n");
      out.write("              <div class=\"inner\">\r\n");
      out.write("                <h4>헌혈로 사랑을 나눠요</h4>\r\n");
      out.write("                <p>레드플러스에서 헌혈 예약을 할 수 있습니다.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <div class=\"item__name\"><a href=\"/view/login/login.jsp\">LOGIN</a></div>\r\n");
      out.write("        </li>\r\n");
      out.write("          <li class=\"item\">\r\n");
      out.write("          <div class=\"item__name\"><a>회원가입</a></div>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <!-- 컨테이너 래퍼 -->\r\n");
      out.write("  <div id=\"container\">\r\n");
      out.write("    <!-- 이너 래퍼-->\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("      <!-- 왼쪽 서브메뉴 래퍼 -->\r\n");
      out.write("      <aside id=\"sub_nav\">\r\n");
      out.write("\r\n");
      out.write("      <!-- 사이드 네비메뉴-->\r\n");
      out.write("      <div class=\"aside_menu\">\r\n");
      out.write("        <div class=\"tit\"><span>마이페이지</span></div>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li class=\"on\"><a href=\"#\">보유헌혈증</a></li>\r\n");
      out.write("          <li class=\"\"><a href=\"#\">헌혈 이력 조회</a></li>\r\n");
      out.write("          <li class=\"\"><a href=\"#\">내가 쓴글 조회</a></li>\r\n");
      out.write("          <li class=\"\"><a href=\"#\">회원정보 수정</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      </aside>\r\n");
      out.write("\r\n");
      out.write("      <!-- 아래부터 메인 컨텐츠(.main_contents) 공간 -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"main_contents\">\r\n");
      out.write("      <!--다들 여기에 작성해주세요-->\r\n");
      out.write("\r\n");
      out.write("	  <!-- 여기는 건들지 마세요!!!!! -->\r\n");
      out.write("      <!-- 작성칸 끝 -->\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- 위는 메인컨텐츠 공간 -->\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--VISUAL-->\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--FOOTER-->\r\n");
      out.write("  <footer>\r\n");
      out.write("    <div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"menu\">\r\n");
      out.write("        <li><a href=\"javascript:void(0)\" class=\"green\">하단메뉴1</a></li>\r\n");
      out.write("        <li><a href=\"javascript:void(0)\">하단메뉴2</a></li>\r\n");
      out.write("        <li><a href=\"javascript:void(0)\">하단메뉴3</a></li>\r\n");
      out.write("        <li><a href=\"javascript:void(0)\">하단메뉴4</a></li>\r\n");
      out.write("        <li><a href=\"javascript:void(0)\">하단메뉴5</a></li>\r\n");
      out.write("        <li><a href=\"javascript:void(0)\">하단메뉴6</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"info\">\r\n");
      out.write("        <span>2023</span>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <p class=\"copyright\">\r\n");
      out.write("        &copy; <span class=\"this-year\"></span> RedPlus. All Rights Reserved.\r\n");
      out.write("      </p>\r\n");
      out.write("      <img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/starbucks_logo_only_text.png\" alt=\"STAR BUCKS\" class=\"logo\" />\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--TO TOP BUTTON-->\r\n");
      out.write("  <div id=\"to-top\">\r\n");
      out.write("    <div class=\"material-icons\">arrow_upward</div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
